version: '3'
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
       - ${PWD}"/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
  app:
    image: "danilnizkiy/test-app:latest"
    network_mode: host
    depends_on:
      - "postgres"
