version: '3'
services:
  app:
    ports:
    - "8080:8080"
    image: "danilnizkiy/test-app:v1"
  redis:
    image: "redis"
    links:
      - postgres
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    image: "postgres"

